# Usa la imagen oficial de Node.js como base
FROM node:16.20.2

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el archivo package.json y package-lock.json (si existe)
# COPY package*.json ./
# Copia el resto de la aplicación
COPY . .

# Instala las dependencias
RUN npm install --force

RUN npm run build

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 1880

# Comando para ejecutar la aplicación
CMD ["npm", "start"]
